default_platform(:ios)

platform :ios do
  desc "Build the app and upload it to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"],
      in_house: false
    )

    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        signingStyle: "manual",
        teamID: ENV["APPLE_TEAM_ID"],
        provisioningProfiles: {
          "ie.automax.app" => ENV["IOS_PROVISIONING_PROFILE_NAME"]
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
