// Towns, villages and city areas for each of the 26 Republic of Ireland counties, alphabetical.
// A long list but not every townland: it is only a help. The Area / Town field lets the customer
// type any place they like.
export const IRISH_TOWNS = {
  Carlow: ['Ballon', 'Borris', 'Carlow', 'Clonegal', 'Fenagh', 'Hacketstown', 'Leighlinbridge', 'Muine Bheag (Bagenalstown)', 'Myshall', 'Rathvilly', 'Tullow'],
  Cavan: ['Arvagh', 'Bailieborough', 'Ballyconnell', 'Ballyjamesduff', 'Belturbet', 'Blacklion', 'Butlersbridge', 'Cavan', 'Cootehill', 'Killeshandra', 'Kingscourt', 'Mullagh', 'Shercock', 'Virginia'],
  Clare: ['Ballyvaughan', 'Bodyke', 'Clarecastle', 'Corofin', 'Cratloe', 'Doolin', 'Ennis', 'Ennistymon', 'Feakle', 'Kilkee', 'Killaloe', 'Kilrush', 'Lahinch', 'Lisdoonvarna', 'Miltown Malbay', 'Mountshannon', 'Newmarket-on-Fergus', 'Quin', 'Scarriff', 'Shannon', 'Sixmilebridge', 'Tulla'],
  Cork: ['Ballincollig', 'Ballycotton', 'Ballydehob', 'Ballyvourney', 'Baltimore', 'Bandon', 'Bantry', 'Blarney', 'Carrigaline', 'Carrigtwohill', 'Castletownbere', 'Castletownroche', 'Charleville', 'Clonakilty', 'Cloyne', 'Cobh', 'Conna', 'Cork City', 'Courtmacsherry', 'Crosshaven', 'Douglas', 'Dunmanway', 'Fermoy', 'Glanmire', 'Kanturk', 'Kinsale', 'Macroom', 'Mallow', 'Midleton', 'Millstreet', 'Mitchelstown', 'Newmarket', 'Passage West', 'Rathcormac', 'Rosscarbery', 'Schull', 'Skibbereen', 'Timoleague', 'Watergrasshill', 'Whitegate', 'Youghal'],
  Donegal: ['Ardara', 'Ballybofey', 'Ballyshannon', 'Buncrana', 'Bundoran', 'Burtonport', 'Carndonagh', 'Carrigart', 'Clonmany', 'Convoy', 'Donegal Town', 'Dunfanaghy', 'Dungloe', 'Falcarragh', 'Glenties', 'Greencastle', 'Gweedore', 'Kilcar', 'Kilmacrennan', 'Killybegs', 'Letterkenny', 'Lifford', 'Malin', 'Moville', 'Mountcharles', 'Pettigo', 'Raphoe', 'Ramelton', 'Rathmullan', 'Stranorlar'],
  Dublin: ['Artane', 'Balbriggan', 'Ballinteer', 'Ballsbridge', 'Ballyfermot', 'Ballymun', 'Blackrock', 'Blanchardstown', 'Booterstown', 'Cabinteely', 'Castleknock', 'Clondalkin', 'Clonsilla', 'Clontarf', 'Coolock', 'Crumlin', 'Dalkey', 'Donabate', 'Drumcondra', 'Dublin City Centre', 'Dundrum', 'Dún Laoghaire', 'Finglas', 'Firhouse', 'Foxrock', 'Glasthule', 'Howth', 'Killiney', 'Kilmainham', 'Leopardstown', 'Lucan', 'Lusk', 'Malahide', 'Monkstown', 'Mulhuddart', 'Newcastle', 'Palmerstown', 'Phibsborough', 'Portmarnock', 'Raheny', 'Rathcoole', 'Rathfarnham', 'Rathgar', 'Rathmines', 'Ringsend', 'Rush', 'Saggart', 'Sandyford', 'Sandymount', 'Santry', 'Shankill', 'Skerries', 'Stillorgan', 'Sutton', 'Swords', 'Tallaght', 'Templeogue', 'Terenure', 'Walkinstown'],
  Galway: ['Athenry', 'Ballinasloe', 'Ballygar', 'Barna', 'Carraroe', 'Claregalway', 'Clarinbridge', 'Clifden', 'Craughwell', 'Dunmore', 'Eyrecourt', 'Galway City', 'Gort', 'Headford', 'Kilconnell', 'Kinvara', 'Leenane', 'Letterfrack', 'Loughrea', 'Moycullen', 'Mountbellew', 'Oranmore', 'Oughterard', 'Portumna', 'Roundstone', 'Salthill', 'Spiddal', 'Tuam', 'Turloughmore', 'Williamstown'],
  Kerry: ['Abbeydorney', 'Annascaul', 'Ardfert', 'Ballybunion', 'Ballyduff', 'Ballyferriter', 'Ballyheigue', 'Blennerville', 'Brosna', 'Cahersiveen', 'Camp', 'Castleisland', 'Castlegregory', 'Dingle', 'Fenit', 'Glenbeigh', 'Kenmare', 'Killarney', 'Killorglin', 'Lispole', 'Listowel', 'Lixnaw', 'Milltown', 'Portmagee', 'Rathmore', 'Sneem', 'Tarbert', 'Tralee', 'Valentia Island', 'Waterville'],
  Kildare: ['Allenwood', 'Athy', 'Ballitore', 'Caragh', 'Carbury', 'Castledermot', 'Celbridge', 'Clane', 'Derrinturn', 'Johnstown', 'Kilcock', 'Kilcullen', 'Kildare', 'Kill', 'Leixlip', 'Maynooth', 'Monasterevin', 'Naas', 'Newbridge', 'Prosperous', 'Rathangan', 'Robertstown', 'Sallins', 'Straffan'],
  Kilkenny: ['Ballyhale', 'Ballyragget', 'Bennettsbridge', 'Callan', 'Castlecomer', 'Dunmore', 'Freshford', 'Goresbridge', 'Gowran', 'Graiguenamanagh', 'Inistioge', 'Johnstown', 'Kells', 'Kilkenny', 'Mooncoin', 'Mullinavat', 'Paulstown', 'Piltown', 'Stoneyford', 'Thomastown', 'Tullaroan', 'Urlingford'],
  Laois: ['Abbeyleix', 'Ballinakill', 'Ballybrittas', 'Ballylinan', 'Ballyroan', 'Borris-in-Ossory', 'Camross', 'Clonaslee', 'Durrow', 'Emo', 'Mountmellick', 'Mountrath', 'Portarlington', 'Portlaoise', 'Rathdowney', 'Rosenallis', 'Stradbally', 'Timahoe', 'Vicarstown'],
  Leitrim: ['Aghavas', 'Ballinamore', 'Carrick-on-Shannon', 'Carrigallen', 'Cloone', 'Dowra', 'Dromahair', 'Drumkeerin', 'Drumshanbo', 'Drumsna', 'Fenagh', 'Glenfarne', 'Jamestown', 'Keshcarrigan', 'Kinlough', 'Kiltyclogher', 'Leitrim Village', 'Manorhamilton', 'Mohill', 'Rooskey'],
  Limerick: ['Abbeyfeale', 'Adare', 'Annacotty', 'Askeaton', 'Athea', 'Ballingarry', 'Ballylanders', 'Broadford', 'Bruff', 'Bruree', 'Cappamore', 'Castleconnell', 'Croom', 'Dooradoyle', 'Dromcollogher', 'Foynes', 'Glin', 'Kilmallock', 'Limerick City', 'Mungret', 'Murroe', 'Newcastle West', 'Oola', 'Pallasgreen', 'Pallaskenry', 'Patrickswell', 'Raheen', 'Rathkeale', 'Shanagolden'],
  Longford: ['Abbeylara', 'Aughnacliffe', 'Ballinalee', 'Ballymahon', 'Clondra', 'Colehill', 'Drumlish', 'Edgeworthstown', 'Granard', 'Keenagh', 'Lanesborough', 'Legan', 'Longford', 'Newtownforbes'],
  Louth: ['Annagassan', 'Ardee', 'Baltray', 'Blackrock', 'Carlingford', 'Castlebellingham', 'Clogherhead', 'Collon', 'Drogheda', 'Dundalk', 'Dunleer', 'Greenore', 'Haggardstown', 'Louth Village', 'Omeath', 'Tallanstown', 'Termonfeckin'],
  Mayo: ['Achill', 'Balla', 'Ballina', 'Ballinrobe', 'Ballindine', 'Ballycastle', 'Ballyhaunis', 'Belmullet', 'Bohola', 'Castlebar', 'Charlestown', 'Claremorris', 'Cong', 'Crossmolina', 'Foxford', 'Hollymount', 'Kilkelly', 'Killala', 'Kiltimagh', 'Knock', 'Louisburgh', 'Mulranny', 'Newport', 'Partry', 'Shrule', 'Swinford', 'Tourmakeady', 'Westport'],
  Meath: ['Ashbourne', 'Athboy', 'Ballivor', 'Bettystown', 'Clonee', 'Donore', 'Drumree', 'Duleek', 'Dunboyne', 'Dunshaughlin', 'Enfield', 'Johnstown', 'Julianstown', 'Kells', 'Kentstown', 'Laytown', 'Longwood', 'Navan', 'Nobber', 'Oldcastle', 'Ratoath', 'Slane', 'Stamullen', 'Summerhill', 'Trim'],
  Monaghan: ['Ballybay', 'Carrickmacross', 'Castleblayney', 'Clones', 'Clontibret', 'Emyvale', 'Glaslough', 'Inniskeen', 'Monaghan', 'Newbliss', 'Rockcorry', 'Scotstown', 'Smithborough'],
  Offaly: ['Banagher', 'Belmont', 'Birr', 'Clara', 'Cloghan', 'Daingean', 'Edenderry', 'Ferbane', 'Geashill', 'Kilcormac', 'Killeigh', 'Kinnitty', 'Moneygall', 'Shannonbridge', 'Shinrone', 'Tullamore'],
  Roscommon: ['Ballaghaderreen', 'Ballinlough', 'Ballintober', 'Boyle', 'Castlerea', 'Cloonfad', 'Croghan', 'Elphin', 'Frenchpark', 'Keadue', 'Knockcroghery', 'Roscommon', 'Strokestown', 'Tarmonbarry', 'Tulsk'],
  Sligo: ['Aclare', 'Ballisodare', 'Ballymote', 'Bunninadden', 'Cliffoney', 'Collooney', 'Coolaney', 'Dromore West', 'Drumcliff', 'Easkey', 'Enniscrone', 'Geevagh', 'Grange', 'Gurteen', 'Mullaghmore', 'Riverstown', 'Rosses Point', 'Sligo', 'Strandhill', 'Tubbercurry'],
  Tipperary: ['Ardfinnan', 'Ballingarry', 'Bansha', 'Borrisokane', 'Borrisoleigh', 'Cahir', 'Cappawhite', 'Carrick-on-Suir', 'Cashel', 'Clogheen', 'Clonmel', 'Cloughjordan', 'Dundrum', 'Emly', 'Fethard', 'Golden', 'Killenaule', 'Littleton', 'Nenagh', 'Newport', 'Roscrea', 'Templemore', 'Thurles', 'Tipperary Town', 'Toomevara'],
  Waterford: ['Abbeyside', 'Aglish', 'Annestown', 'Ardmore', 'Bunmahon', 'Cappoquin', 'Cheekpoint', 'Clashmore', 'Dungarvan', 'Dunmore East', 'Ferrybank', 'Kill', 'Kilmacthomas', 'Lismore', 'Passage East', 'Portlaw', 'Rathgormack', 'Stradbally', 'Tallow', 'Tramore', 'Waterford City'],
  Westmeath: ['Athlone', 'Ballymore', 'Ballynacargy', 'Castlepollard', 'Clonmellon', 'Collinstown', 'Delvin', 'Kilbeggan', 'Killucan', 'Kinnegad', 'Moate', 'Mullingar', 'Multyfarnham', 'Raharney', 'Rochfortbridge', 'Tyrrellspass'],
  Wexford: ['Adamstown', 'Bridgetown', 'Bunclody', 'Camolin', 'Campile', 'Castlebridge', 'Clonroche', 'Courtown', 'Duncannon', 'Enniscorthy', 'Ferns', 'Fethard-on-Sea', 'Gorey', 'Kilmore Quay', 'Kilmuckridge', 'New Ross', 'Oulart', 'Rosslare', 'Rosslare Harbour', 'Taghmon', 'Wellingtonbridge', 'Wexford'],
  Wicklow: ['Arklow', 'Ashford', 'Aughrim', 'Avoca', 'Baltinglass', 'Blessington', 'Bray', 'Brittas Bay', 'Carnew', 'Delgany', 'Donard', 'Dunlavin', 'Enniskerry', 'Glendalough', 'Greystones', 'Kilcoole', 'Kilmacanogue', 'Laragh', 'Newtownmountkennedy', 'Rathdrum', 'Rathnew', 'Redcross', 'Roundwood', 'Shillelagh', 'Tinahely', 'Valleymount', 'Wicklow'],
};

// keep every county's list alphabetical for the dropdown
for (const county of Object.keys(IRISH_TOWNS)) IRISH_TOWNS[county].sort((a, b) => a.localeCompare(b, 'en'));
